CLOSURE_FLAGS := --compilation_level WHITESPACE_ONLY --formatting PRETTY_PRINT

.DEFAULT_GOAL := all
#CONFIG_PATH := uploader/config.js

VPATH = ../client
include ../client/Makefile

all: client

.PHONY: all
